/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;

import Logica.crudCliente_Logica;

/**
 *
 * @author crist
 */
public class logicaNegocio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(logicaNegocio.class.getName());
    private static crudCliente_Logica crud;

    /**
     * Creates new form logicaNegocio
     */
    public logicaNegocio(crudCliente_Logica crud) {

        initComponents();
        this.crud = crud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroMesasTextField1 = new javax.swing.JTextField();
        ingresarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el numero de mesas:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Logica del negocio");

        numeroMesasTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroMesasTextField1ActionPerformed(evt);
            }
        });

        ingresarBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresarBTN.setText("Ingresar");
        ingresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(ingresarBTN, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(numeroMesasTextField1))
                                                .addGap(114, 114, 114)))
                                .addContainerGap(74, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numeroMesasTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48,
                                        Short.MAX_VALUE)
                                .addComponent(ingresarBTN)
                                .addGap(54, 54, 54)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ingresarBTNActionPerformed

        // no me alcanzo el tiempo para hacer la funcion
        boolean valid = false;
        String numeroMesas = numeroMesasTextField1.getText().trim();

        // pa validar si no esta vacio o es letras
        while (!valid) {
            if (numeroMesas.isEmpty()) {
                numeroMesas = JOptionPane.showInputDialog(null,
                        "El numero de mesas no puede estar vacio, ingrese un numero valido");
                if (numeroMesas == null) {
                    JOptionPane.showMessageDialog(null, "Registro cancelado.");
                    return;
                }
            } else {
                try {
                    int num = Integer.parseInt(numeroMesas);
                    if (num <= 0) {
                        numeroMesas = JOptionPane.showInputDialog(null,
                                "El numero de mesas debe ser mayor a cero, ingrese un numero valido");
                        if (numeroMesas == null) {
                            JOptionPane.showMessageDialog(null, "Registro cancelado.");
                            return;
                        }
                    } else {
                        valid = true;
                    }
                } catch (NumberFormatException e) {
                    numeroMesas = JOptionPane.showInputDialog(null,
                            "El numero de mesas debe ser un numero, no letras, ingrese un numero valido");
                    if (numeroMesas == null) {
                        JOptionPane.showMessageDialog(null, "Registro cancelado.");
                        return;
                    }
                }
            }
        }

        // este es el que se va a guardar
        int numMesa = Integer.parseInt(numeroMesas);

        crud.llenarMatriz(numMesa);
        registrarCliente_Interfaz ventana = new registrarCliente_Interfaz(crud, numMesa);
        ventana.setVisible(true);
        dispose();

    }// GEN-LAST:event_ingresarBTNActionPerformed

    private void numeroMesasTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numeroMesasTextField1ActionPerformed

    }// GEN-LAST:event_numeroMesasTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new logicaNegocio(crud).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numeroMesasTextField1;
    // End of variables declaration//GEN-END:variables
}
