/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.crudCliente_Logica;

/**
 *
 * @author crist
 */
public class logicaNegocio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(logicaNegocio.class.getName());

    /**
     * Creates new form logicaNegocio
     */
    public logicaNegocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        domingosCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        mesasDisponiblesTextField1 = new javax.swing.JTextField();
        confirmarLogicaNegocioBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("configurar parametros principales");

        jLabel2.setText("va atender los domingos?");

        domingosCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domingosCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("cuantas mesas hay?");

        mesasDisponiblesTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesasDisponiblesTextField1ActionPerformed(evt);
            }
        });

        confirmarLogicaNegocioBTN.setText("Confirmar");
        confirmarLogicaNegocioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarLogicaNegocioBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(90, 90, 90))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmarLogicaNegocioBTN)
                                        .addComponent(domingosCheckBox1)
                                        .addComponent(mesasDisponiblesTextField1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(124, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(domingosCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(mesasDisponiblesTextField1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65,
                                        Short.MAX_VALUE)
                                .addComponent(confirmarLogicaNegocioBTN)
                                .addGap(52, 52, 52)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    crudCliente_Logica crud = new crudCliente_Logica();

    private void domingosCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_domingosCheckBox1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_domingosCheckBox1ActionPerformed

    private void mesasDisponiblesTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesasDisponiblesTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mesasDisponiblesTextField1ActionPerformed

    private void confirmarLogicaNegocioBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmarLogicaNegocioBTNActionPerformed

        int dias;

        if (domingosCheckBox1.isSelected()) {
            dias = 7;

        } else {
            dias = 6;

        }
        int mesas = Integer.parseInt(mesasDisponiblesTextField1.getText());

        crud.ingresarLogicaNegocio(mesas, dias);

        menuInicio menu = new menuInicio(crud, mesas, dias);
        menu.setVisible(true);

        dispose();
    }// GEN-LAST:event_confirmarLogicaNegocioBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new logicaNegocio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarLogicaNegocioBTN;
    private javax.swing.JCheckBox domingosCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mesasDisponiblesTextField1;
    // End of variables declaration//GEN-END:variables
}
