package Interfaz;

import java.time.LocalDateTime;

import Logica.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author crist
 */
public class menuInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(menuInicio.class.getName());
    private static crudCliente_Logica crud;

    /**
     * Creates new form Inicio
     */
    public menuInicio(crudCliente_Logica crud) {
        initComponents();
        this.crud = crud;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultarClientesBTN = new javax.swing.JButton();
        ingresarClienteBTN = new javax.swing.JButton();
        totalClientesSemana = new javax.swing.JButton();
        totalClientesDia = new javax.swing.JButton();
        clientesMesas = new javax.swing.JButton();
        diaMaximoClientes = new javax.swing.JButton();
        buscarCedulaBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Cafe la Esquina");

        consultarClientesBTN.setText("Consultar Clientes");
        consultarClientesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarClientesBTNActionPerformed(evt);
            }
        });

        ingresarClienteBTN.setText("Ingresar Cliente");
        ingresarClienteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarClienteBTNActionPerformed(evt);
            }
        });

        totalClientesSemana.setText("Total Clientes Semana");
        totalClientesSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalClientesSemanaActionPerformed(evt);
            }
        });

        totalClientesDia.setText("Total Clientes Día");
        totalClientesDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalClientesDiaActionPerformed(evt);
            }
        });

        clientesMesas.setText("Total Clientes mesa");
        clientesMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesMesasActionPerformed(evt);
            }
        });

        diaMaximoClientes.setText("Día con más Clientes");
        diaMaximoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaMaximoClientesActionPerformed(evt);
            }
        });

        buscarCedulaBTN.setText("Buscar por numero de cedula");
        buscarCedulaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCedulaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(totalClientesSemana,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(clientesMesas,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ingresarClienteBTN,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44,
                                                        Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(consultarClientesBTN,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 165,
                                                                Short.MAX_VALUE)
                                                        .addComponent(totalClientesDia,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(diaMaximoClientes,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(154, 154, 154)
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(buscarCedulaBTN)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(consultarClientesBTN)
                                        .addComponent(ingresarClienteBTN))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalClientesSemana)
                                        .addComponent(totalClientesDia))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clientesMesas)
                                        .addComponent(diaMaximoClientes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38,
                                        Short.MAX_VALUE)
                                .addComponent(buscarCedulaBTN)
                                .addGap(27, 27, 27)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalClientesSemanaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalClientesSemanaActionPerformed
        crud.totalClientesSemanales();
    }// GEN-LAST:event_totalClientesSemanaActionPerformed

    private void totalClientesDiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalClientesDiaActionPerformed
        crud.totalClientesPorDiaSemana();
    }// GEN-LAST:event_totalClientesDiaActionPerformed

    private void clientesMesasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clientesMesasActionPerformed
        crud.totalClientesPorMesa();
    }// GEN-LAST:event_clientesMesasActionPerformed

    private void diaMaximoClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diaMaximoClientesActionPerformed
        crud.diaConMasClientes();
    }// GEN-LAST:event_diaMaximoClientesActionPerformed

    private void buscarCedulaBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscarCedulaBTNActionPerformed

        crud.consultarID();

    }// GEN-LAST:event_buscarCedulaBTNActionPerformed

    private void ingresarClienteBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ingresarClienteBTNActionPerformed

        // abrir la ventana de registrar cliente y le mandarle el objeto crud para que
        // no sea diferente
        registrarCliente_Interfaz registrar = new registrarCliente_Interfaz(crud);
        registrar.setVisible(true);
        dispose();

    }// GEN-LAST:event_ingresarClienteBTNActionPerformed

    private void consultarClientesBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_consultarClientesBTNActionPerformed

        crud.consultar();

    }// GEN-LAST:event_consultarClientesBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuInicio(crud).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCedulaBTN;
    private javax.swing.JButton clientesMesas;
    private javax.swing.JButton consultarClientesBTN;
    private javax.swing.JButton diaMaximoClientes;
    private javax.swing.JButton ingresarClienteBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton totalClientesDia;
    private javax.swing.JButton totalClientesSemana;
    // End of variables declaration//GEN-END:variables
}
