/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class registrarCliente_Interfaz extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(registrarCliente_Interfaz.class.getName());
        private static crudCliente_Logica crud;
        private static int numeroMesas;
        private static int dias;

        /**
         * Creates new form inicioMenu
         */
        public registrarCliente_Interfaz(crudCliente_Logica crud, int numeroMesas, int dias) {
                initComponents();
                this.crud = crud;
                this.numeroMesas = numeroMesas;
                this.dias = dias;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                documentoTextField = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                mesaUbicacionTextField = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                diaReservaTextField1 = new javax.swing.JTextField();
                ingresarCliente = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                nombreClienteTextField1 = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Cafe la Esquina Reservaciones");

                documentoTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                documentoTextFieldActionPerformed(evt);
                        }
                });

                jLabel2.setText("Ingrese numero de documento:");

                jLabel3.setText("Mesa donde se ubicara la persona:");

                mesaUbicacionTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mesaUbicacionTextFieldActionPerformed(evt);
                        }
                });

                jLabel4.setText("Dia de la semana que se reservara:");

                diaReservaTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                diaReservaTextField1ActionPerformed(evt);
                        }
                });

                ingresarCliente.setText("Ingresar Cliente");
                ingresarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ingresarClienteActionPerformed(evt);
                        }
                });

                jLabel5.setText("Ingrese el nombre del cliente");

                nombreClienteTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nombreClienteTextField1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(150, 150, 150)
                                                                                                .addComponent(ingresarCliente))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(125, 125, 125)
                                                                                                .addComponent(jLabel1)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGap(12, 12, 12)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(documentoTextField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                167, Short.MAX_VALUE)
                                                                                .addComponent(diaReservaTextField1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                167, Short.MAX_VALUE)
                                                                                .addComponent(mesaUbicacionTextField)
                                                                                .addComponent(nombreClienteTextField1))
                                                                .addGap(48, 48, 48)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addGap(61, 61, 61)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(nombreClienteTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(documentoTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                16,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(mesaUbicacionTextField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(diaReservaTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ingresarCliente)
                                                                .addContainerGap(70, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void nombreClienteTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreClienteTextField1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_nombreClienteTextField1ActionPerformed

        private void ingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ingresarClienteActionPerformed

                LocalDateTime horaIngreso = LocalDateTime.now();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm a");
                String horaFormateada = dtf.format(horaIngreso);

                String nombreCliente = nombreClienteTextField1.getText();
                String numeroDocumento = documentoTextField.getText();
                try {

                        while (nombreCliente.isEmpty()) {

                                nombreCliente = JOptionPane.showInputDialog(null,
                                                "El nombre del cliente no puede estar vacio, ingrese un nombre valido");

                        }

                        while (numeroDocumento.isEmpty() || Integer.parseInt(numeroDocumento) < 999) {

                                numeroDocumento = JOptionPane.showInputDialog(null,
                                                "El numero de documento no puede estar vacio o ser menores a cuatro digitos, ingrese un numero valido valido");

                        }

                } catch (Exception e) {
                        System.out.println(e);
                }

                int numeroMesaIngresado = Integer.parseInt(mesaUbicacionTextField.getText());

                try {

                        while (numeroMesaIngresado < 1 || numeroMesaIngresado > numeroMesas) {

                                numeroMesaIngresado = Integer.parseInt(JOptionPane.showInputDialog(null,
                                                "recuerde que las mesas disponibles son de la 1 a la " + numeroMesas));

                        }

                } catch (Exception e) {
                        System.out.println(e);
                }

                String diaReserva = diaReservaTextField1.getText().toLowerCase();
                int diaSemana = -1;

                try {

                        boolean error = false;
                        diaSemana = -1;
                        while (diaSemana <= -1 || diaSemana > (dias - 1)) {

                                switch (diaReserva) {
                                        case "lunes" -> diaSemana = 0;
                                        case "martes" -> diaSemana = 1;
                                        case "miercoles" -> diaSemana = 2;
                                        case "jueves" -> diaSemana = 3;
                                        case "viernes" -> diaSemana = 4;
                                        case "sabado" -> diaSemana = 5;
                                        case "domingo" -> diaSemana = 6;
                                        default -> {
                                                diaReserva = JOptionPane.showInputDialog(null,
                                                                "dia no valido escriba el dia sin tildes y con letras");
                                                error = true;
                                        }
                                }

                                if (error != true) {
                                        if (diaSemana < 0 || diaSemana > (dias - 1)) {
                                                diaReserva = JOptionPane.showInputDialog(null,
                                                                "dia no valido recuerde que hoy tabajamos de lunes a "
                                                                                + crud.saberDiasLetra(dias - 1));
                                        }

                                }

                        }

                } catch (Exception e) {

                        System.out.println(e);

                }

                Persona cliente = new Persona(Integer.parseInt(numeroDocumento), diaSemana, horaFormateada,
                                numeroMesaIngresado - 1, nombreCliente);

                crud.ingresarCliente(cliente);

                menuInicio menu = new menuInicio(crud, numeroMesas, dias);
                menu.setVisible(true);
                dispose();

        }// GEN-LAST:event_ingresarClienteActionPerformed

        private void documentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_documentoTextFieldActionPerformed

        }// GEN-LAST:event_documentoTextFieldActionPerformed

        private void diaReservaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diaIngresoTextField1ActionPerformed

        }// GEN-LAST:event_diaIngresoTextField1ActionPerformed

        private void mesaUbicacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesaUbicacionTextFieldActionPerformed

        }// GEN-LAST:event_mesaUbicacionTextFieldActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(
                                () -> new registrarCliente_Interfaz(crud, numeroMesas, dias).setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField diaReservaTextField1;
        private javax.swing.JTextField documentoTextField;
        private javax.swing.JButton ingresarCliente;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JTextField mesaUbicacionTextField;
        private javax.swing.JTextField nombreClienteTextField1;
        // End of variables declaration//GEN-END:variables
}
