/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class registrarCliente_Interfaz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(registrarCliente_Interfaz.class.getName());
    private static crudCliente_Logica crud;

    /**
     * Creates new form inicioMenu
     */
    public registrarCliente_Interfaz(crudCliente_Logica crud) {
        initComponents();
        this.crud = crud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        documentoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nombreClienteTextField1 = new javax.swing.JTextField();
        mesaComboBox = new javax.swing.JComboBox<>();
        diaComboBox = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cafe la Esquina Reservaciones");

        documentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese numero de documento:");

        jLabel3.setText("Mesa donde se ubicara la persona:");

        jLabel4.setText("Dia de la semana que se reservara:");

        ingresarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ingresarCliente.setText("Ingresar Cliente");
        ingresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese el nombre del cliente");

        nombreClienteTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteTextField1ActionPerformed(evt);
            }
        });

        mesaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Mesa 1", "mesa 2", "Mesa 3", "Mesa 4", "Mesa 5" }));
        mesaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesaComboBoxActionPerformed(evt);
            }
        });

        diaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        diaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(ingresarCliente)
                                .addContainerGap(138, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(documentoTextField,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 167,
                                                                Short.MAX_VALUE)
                                                        .addComponent(nombreClienteTextField1)
                                                        .addComponent(mesaComboBox, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(diaComboBox, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(48, 48, 48)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(nombreClienteTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(documentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(diaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
                                        Short.MAX_VALUE)
                                .addComponent(ingresarCliente)
                                .addGap(33, 33, 33)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mesaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesaComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_mesaComboBoxActionPerformed

    private void diaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diaComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_diaComboBoxActionPerformed

    private void nombreClienteTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreClienteTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nombreClienteTextField1ActionPerformed

    private void ingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ingresarClienteActionPerformed

        // tomar la hora actual y formatearla
        LocalDateTime horaIngreso = LocalDateTime.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("hh:mm a");
        String horaFormateada = dtf.format(horaIngreso);

        // tomar los datos de los campos
        String nombreCliente = nombreClienteTextField1.getText();
        String numeroDocumentoIngresado = documentoTextField.getText().trim();
        int numeroMesaIngresado = mesaComboBox.getSelectedIndex() + 1;

        String diaReserva = diaComboBox.getSelectedItem().toString().toLowerCase();
        int diaSemana = 0;
        diaSemana = crud.saberDiasNumero(diaReserva, diaSemana);

        // que no esten vacios los campos
        while (nombreCliente.isEmpty()) {

            nombreCliente = JOptionPane.showInputDialog(null,
                    "El nombre del cliente no puede estar vacio, ingrese un nombre valido");

        }
        while (numeroDocumentoIngresado.isEmpty()) {

            numeroDocumentoIngresado = JOptionPane.showInputDialog(null,
                    "El numero de documento no puede estar vacio o ser menor a cero, ingrese un numero valido valido");

        }
        int numeroDocumento = Integer.parseInt(numeroDocumentoIngresado);

        // crear el objeto cliente y agregarlo a la lista

        Persona cliente = new Persona(numeroDocumento, diaSemana, horaFormateada,
                numeroMesaIngresado - 1, nombreCliente);

        crud.ingresarCliente(cliente);

        // volver al menu principal
        menuInicio menu = new menuInicio(crud);
        menu.setVisible(true);
        dispose();

    }// GEN-LAST:event_ingresarClienteActionPerformed

    private void documentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_documentoTextFieldActionPerformed

    }// GEN-LAST:event_documentoTextFieldActionPerformed

    private void diaReservaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diaIngresoTextField1ActionPerformed

    }// GEN-LAST:event_diaIngresoTextField1ActionPerformed

    private void mesaUbicacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesaUbicacionTextFieldActionPerformed

    }// GEN-LAST:event_mesaUbicacionTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                () -> new registrarCliente_Interfaz(crud).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> diaComboBox;
    private javax.swing.JTextField documentoTextField;
    private javax.swing.JButton ingresarCliente;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mesaComboBox;
    private javax.swing.JTextField nombreClienteTextField1;
    // End of variables declaration//GEN-END:variables
}
